name: fet

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['^1.8.0-0', 'nightly']
        os: [ubuntu-latest, macOS-latest]
    
    steps:
      - uses: actions/checkout@v1.0.0
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - run: make -C ./test/cref && julia --project ./test/runtests.jl -e 'using Pkg; Pkg.add("SpecialFunctions")'
        shell: bash
